curl -H Accept:text/event-stream http://localhost:3000/chat/sse

### Load Conflu page
POST http://localhost:3000/document/load HTTP/1.1
Content-Type: application/json

{
  "baseUrl": "https://startuphouse.atlassian.net/wiki",
  "spaceKey": "SDH"
}

### ChromaDB
GET http://localhost:8000/api/v1/collections HTTP/1.1

### ChromaDB
DELETE  http://localhost:8000/api/v1/collections/SDH HTTP/1.1

